spring.application.name=doda
server.port=8081
#spring.datasource.url=jdbc:mysql://localhost:3306/doda?useSSL=false&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://localhost:3306/doda?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Ctl060906
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis ??
mybatis.mapper-locations=classpath:mapper/*.xml